//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using ShrinkageExplorer.Core.Interfaces;

namespace ShrinkageExplorer.Data
{
  using System;
  using System.Collections.Generic;

  public partial class Line
  {
    public Line()
    {
      this.Drives = new ObservableCollection<IRollDrive>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public float AirTemperature { get; set; }
    public float AirCoefficient { get; set; }
    public float RollCoefficient { get; set; }

    public virtual IList<IRollDrive> Drives { get; set; }
  }
}
