//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShrinkageExplorer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialParameter
    {
        public int ParameterID { get; set; }
        public int MaterialID { get; set; }
        public string Value { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Parameter Parameter { get; set; }
    }
}
