//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;

namespace ShrinkageExplorer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public Parameter()
        {
            this.MaterialParameters = new ObservableCollection<MaterialParameter>();
            this.Models = new ObservableCollection<Model>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<MaterialParameter> MaterialParameters { get; set; }
        public virtual ICollection<Model> Models { get; set; }
    }
}
