//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShrinkageExplorer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShrinkageEntities : DbContext
    {
        public ShrinkageEntities()
            : base("name=ShrinkageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Drive> Drives { get; set; }
        public DbSet<Line> Lines { get; set; }
        public DbSet<Roll> Rolls { get; set; }
        public DbSet<MaterialParameter> MaterialParameters { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<Parameter> Parameters { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
